// テスト用のモック商品データ
export const mockProducts = [
  {
    id: "buddhist-001",
    name: "季節の仏花・春",
    price: 3800,
    original_price: null,
    image_url: "/flowers/buddhist-01.jpg",
    category: "buddhist",
    description:
      "春の訪れを感じる美しい仏花アレンジメントです。桜や菜の花など、春らしい花材を使用しています。",
    tags: ["季節限定", "春"],
    rating: 4.5,
    reviews: 92,
    color: "pink",
    size: "medium",
    flower: "mixed",
    specifications: {
      dimensions: "幅15cm × 奥行き15cm × 高さ20cm",
      weight: "約300g",
      vase_material: "陶器",
      flower_types: "桜、菜の花、チューリップ、スイートピー",
      preservation_method: "プリザーブド加工",
      care_instructions: "直射日光を避け、湿度の低い場所で保管",
      lifespan: "2-3年",
      packaging: "専用ギフトボックス付き",
    },
    is_new: false,
    is_sale: false,
    is_active: true,
    created_at: "2025-01-09T00:00:00.000Z",
    updated_at: "2025-01-09T00:00:00.000Z",
  },
  {
    id: "buddhist-002",
    name: "仏花・白蓮",
    price: 4200,
    original_price: null,
    image_url: "/flowers/buddhist-02.jpg",
    category: "buddhist",
    description:
      "清らかな白蓮を中心とした仏花です。心を落ち着かせる美しいアレンジメントです。",
    tags: ["白蓮", "清らか"],
    rating: 4.7,
    reviews: 78,
    color: "white",
    size: "medium",
    flower: "lotus",
    specifications: {
      dimensions: "幅18cm × 奥行き18cm × 高さ25cm",
      weight: "約400g",
      vase_material: "白磁",
      flower_types: "白蓮、白いカーネーション、白いバラ",
      preservation_method: "プリザーブド加工",
      care_instructions: "直射日光を避け、湿度の低い場所で保管",
      lifespan: "2-3年",
      packaging: "白い専用ギフトボックス付き",
    },
    is_new: false,
    is_sale: false,
    is_active: true,
    created_at: "2025-01-09T00:00:00.000Z",
    updated_at: "2025-01-09T00:00:00.000Z",
  },
  {
    id: "preserved-001",
    name: "プリザーブドローズ・エレガント",
    price: 12800,
    original_price: null,
    image_url: "/flowers/preserved-01.jpg",
    category: "preserved",
    description:
      "エレガントなプリザーブドローズのアレンジメントです。長期間美しさを保ちます。",
    tags: ["新作", "ギフト"],
    rating: 4.9,
    reviews: 89,
    color: "red",
    size: "medium",
    flower: "rose",
    specifications: {
      dimensions: "幅20cm × 奥行き20cm × 高さ30cm",
      weight: "約500g",
      vase_material: "ガラス",
      flower_types: "赤いバラ、ピンクのバラ、白いバラ",
      preservation_method: "プリザーブド加工",
      care_instructions: "直射日光を避け、湿度の低い場所で保管。水やり不要",
      lifespan: "3-5年",
      packaging: "高級ギフトボックス付き",
    },
    is_new: true,
    is_sale: false,
    is_active: true,
    created_at: "2025-01-09T00:00:00.000Z",
    updated_at: "2025-01-09T00:00:00.000Z",
  },
  {
    id: "preserved-002",
    name: "プリザーブド・ハートボックス",
    price: 9800,
    original_price: null,
    image_url: "/flowers/preserved-02.jpg",
    category: "preserved",
    description:
      "ハート型のボックスに入ったロマンチックなプリザーブドフラワーです。",
    tags: ["記念日", "贈り物"],
    rating: 4.8,
    reviews: 134,
    color: "pink",
    size: "small",
    flower: "mixed",
    specifications: {
      dimensions: "幅12cm × 奥行き12cm × 高さ15cm",
      weight: "約200g",
      vase_material: "ハート型アクリルボックス",
      flower_types: "ピンクのバラ、白いバラ、ベビーブレス",
      preservation_method: "プリザーブド加工",
      care_instructions: "直射日光を避け、湿度の低い場所で保管。水やり不要",
      lifespan: "2-3年",
      packaging: "ハート型ギフトボックス付き",
    },
    is_new: false,
    is_sale: false,
    is_active: true,
    created_at: "2025-01-09T00:00:00.000Z",
    updated_at: "2025-01-09T00:00:00.000Z",
  },
];
